@extends('layouts.backend')

@section('content')
                    
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
                    <p>usuaris</p>
@endsection
