@extends('layouts.backend')

@section('content')
                    
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
                    <p>analytics</p>
@endsection
